### PR TITLE
Add "packsides" command which deduplicates identical sidedefs

### PR DESCRIPTION
**Pull request by pwiecz**
It requires preprocessing linedefs before writing them down, so the Wad.run() becomes perhaps a little less clean. :(

### CODE REVIEW

**Comment by jmtd** [comment]
Thank you for this. I haven't forgotten about it, but I haven't had time for WadC for a while. I hope to get to it sometime soon!

**Comment by jmtd** [comment]
It passes the "look" test, code looks good! Next check is the example WAD checksum check - all of the examples have changed in some way after this patch and the checksums don't match. So the next, more involved, check is for me to look at which bits of the WADs changed, and whether that's OK.

**Comment by pwiecz** [comment]
I can also take a look and see what were the changes.

**Comment by pwiecz** [comment]
I've looked at the checksum diffs, they come from two sources:
- I change the order of sidedefs. If I sort them again restoring their original ordering almost all diffs go away
- linedef pruning is a bit more "aggressive" now, as it also prunes sidedefs referenced by linedefs being pruned. If I added those sidedefs to sidedef list the last remaining diff "examples/hexagon.wl" goes away.

Still I think that there was a bug in the pull request, as the check for pruning lines was performed only for linedefs with no sidedefs defined and it was not applied to linedefs with the same sector on both sides.

As only "hexagon.wl" of all the tests is using the "prunelines" option it was not caught by the test suite...

**Comment by jmtd** [comment]
Thanks for digging!

> I change the order of sidedefs. If I sort them again restoring their original ordering almost all diffs go away

Good to know. No need to sort them, but we should update the checksums for those WADs.

> linedef pruning is a bit more "aggressive" now, as it also prunes sidedefs referenced by linedefs being pruned. If I added those sidedefs to sidedef list the last remaining diff "examples/hexagon.wl" goes away.

Likewise if this cleans up orphaned sidedefs it's worth preserving the PR's behaviour and updating the checksums instead.

> Still I think that there was a bug in the pull request, as the check for pruning lines was performed only for linedefs with no sidedefs defined and it was not applied to linedefs with the same sector on both sides.

Good catch! Thanks.

So The PR is good to go with an update to the sha1sums file (run `make sha1sums` and commit the result). If you give me write access to your fork I can push that to the PR myself.

Happy New Year!

**Comment by pwiecz** [comment]
I think the option "Allow edits from maintainers" was alread enabled. Is it enough?

Happy New Year! :)

**Comment by jmtd** [comment]
> I think the option "Allow edits from maintainers" was alread enabled. Is it enough?

Thanks -- hadn't realised it was already on. Yep I could push the update, great!

**Pull request merged**
